# Generated by Django 2.1.1 on 2018-10-10 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('regular', 'Regular'), ('image', 'Image'), ('url', 'URL')], default='regular', editable=False, max_length=1)),
                ('trash', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImageNote',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.Note')),
                ('url', models.TextField()),
                ('stored_path', models.TextField(default='/', editable=False, null=True)),
            ],
            bases=('notes.note',),
        ),
        migrations.CreateModel(
            name='LinkNote',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.Note')),
                ('url', models.TextField()),
            ],
            bases=('notes.note',),
        ),
        migrations.CreateModel(
            name='RegularNote',
            fields=[
                ('note_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.Note')),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('color', models.CharField(choices=[('#ffffff', 'White'), ('#ffc5c0', 'Red'), ('#b7e9ff', 'Blue'), ('#cfd8dc', 'Grey')], default='#ffffff', max_length=7, null=True)),
            ],
            bases=('notes.note',),
        ),
    ]
